spring:
  application:
    name: game
  datasource:
    url: jdbc:mysql://rm-bp10p106cd0u31dm96o.mysql.rds.aliyuncs.com:3306/admintest?suseUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: dongdong
    password: Ywd213886
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #初始化，最小，最大连接数
      initial-size: 10
      max-active: 30
      min-idle: 10
      #获取数据库连接等待的超时时间
      max-wait: 60000
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM dual
      filters: stat,wall,log4j
      min-evictable-idle-time-millis: 180000
      keep-alive: true
  jpa:
    database: MySQL
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  redis:
#    host: 139.224.255.39
#    port: 6379
#    database: 1
#    password:
#    jedis:
#      pool:
#        #最大连接数量
#        max-active: 200
#        #最大空闲数量
#        max-idle: 200
#        #最小空闲数量
#        min-idle: 10
#        #最大等待时间
#        max-wait: 3000ms
server:
  port: 8585
#logging:
#  config: classpath:logback-spring.xml
#  file:
#    path: log/adminlog
